# Entrypoint for helm automation
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./kuttl/tests/helm
parallel: 3
timeout: 8120
startKIND: false
artifactsDir: kuttl-artifacts
kindNodeCache: false
